---
- hosts: service
  become: true

  tasks:
  - name: Copy file log
    copy:
      src: ./files/watchlog.log
      dest: /var/log/watchlog.log

  - name: Copy file cfg
    copy:
      src: ./files/watchlog.cfg
      dest: /etc/sysconfig/watchlog

  - name: Copy file sh
    copy:
      src: ./files/watchlog.sh
      dest: /opt/watchlog.sh
      mode: u+x

  - name: Copy file service watchlog
    copy:
      src: ./files/watchlog.service
      dest: /etc/systemd/system/watchlog.service

  - name: Copy file timer watchlog
    copy:
      src: ./files/watchlog.timer
      dest: /etc/systemd/system/watchlog.timer

  - name: Timer start timer
    systemd:
      name: watchlog.timer
      state: started
      enabled: true

  - name: Timer start service
    systemd:
      name: watchlog.service
      state: started
